// <auto-generated />
using System;
using DataEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEF.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataEF.Models.Bracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Category")
                        .HasColumnType("decimal(3, 1)");

                    b.HasKey("Id")
                        .HasName("PK__Brackets__3214EC072D3868F9");

                    b.HasIndex(new[] { "Id" }, "UQ__Brackets__3214EC06A41D6B88")
                        .IsUnique();

                    b.HasIndex(new[] { "Category" }, "UQ__Brackets__4BB73C3294543B29")
                        .IsUnique();

                    b.ToTable("Brackets");
                });

            modelBuilder.Entity("DataEF.Models.Ledger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BracketId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Ledgers__3214EC0767890A07");

                    b.HasIndex("BracketId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex(new[] { "Id" }, "UQ__Ledgers__3214EC069CE6108D")
                        .IsUnique();

                    b.ToTable("Ledgers");
                });

            modelBuilder.Entity("DataEF.Models.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Municipa__3214EC079BF33FDA");

                    b.HasIndex(new[] { "Id" }, "UQ__Municipa__3214EC060EDFBC96")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "UQ__Municipa__737584F66F6049D6")
                        .IsUnique();

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("DataEF.Models.Ledger", b =>
                {
                    b.HasOne("DataEF.Models.Bracket", "Bracket")
                        .WithMany("Ledgers")
                        .HasForeignKey("BracketId")
                        .IsRequired()
                        .HasConstraintName("FK_Brackets_Ledgers");

                    b.HasOne("DataEF.Models.Municipality", "Municipality")
                        .WithMany("Ledgers")
                        .HasForeignKey("MunicipalityId")
                        .IsRequired()
                        .HasConstraintName("FK_Municipalities_Ledgers");

                    b.Navigation("Bracket");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("DataEF.Models.Bracket", b =>
                {
                    b.Navigation("Ledgers");
                });

            modelBuilder.Entity("DataEF.Models.Municipality", b =>
                {
                    b.Navigation("Ledgers");
                });
#pragma warning restore 612, 618
        }
    }
}
